In [1]:
import pandas as pd
import numpy as np
import datetime
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore",category=DeprecationWarning)
    import sklearn

In [2]:
epd_df = pd.read_csv("EPD.csv", encoding='utf-8')
epd_df.rename(columns={"Open":"Open_EPD", "Close": "Close_EPD"}, inplace = True)
epd_df["Monthly_Change_EPD"] = epd_df["Open_EPD"] - epd_df["Close_EPD"]

kmi_df = pd.read_csv("KMI.csv", encoding='utf-8')
kmi_df.rename(columns={"Open":"Open_KMI", "Close": "Close_KMI"}, inplace = True)
kmi_df["Monthly_Change_KMI"] = kmi_df["Open_KMI"] - kmi_df["Close_KMI"]
kmi_df = kmi_df.drop(columns=["Date"])

mmp_df = pd.read_csv("MMP.csv", encoding='utf-8')
mmp_df.rename(columns={"Open":"Open_MMP", "Close": "Close_MMP"}, inplace = True)
mmp_df["Monthly_Change_MMP"] = mmp_df["Open_MMP"] - mmp_df["Close_MMP"]
mmp_df = mmp_df.drop(columns=["Date"])

mplx_df = pd.read_csv("MPLX.csv", encoding='utf-8')
mplx_df.rename(columns={"Open":"Open_MPLX", "Close": "Close_MPLX"}, inplace = True)
mplx_df["Monthly_Change_MPLX"] = mplx_df["Open_MPLX"] - mplx_df["Close_MPLX"]
mplx_df = mplx_df.drop(columns=["Date"])

et_df = pd.read_csv("ET.csv", encoding='utf-8')
et_df.rename(columns={"Open":"Open_ET", "Close": "Close_ET"}, inplace = True)
et_df["Monthly_Change_ET"] = et_df["Open_ET"] - et_df["Close_ET"]
et_df = et_df.drop(columns=["Date"])

xom_df = pd.read_csv("XOM.csv", encoding='utf-8')
xom_df.rename(columns={"Open":"Open_XOM", "Close": "Close_XOM"}, inplace = True)
xom_df["Monthly_Change_XOM"] = xom_df["Open_XOM"] - xom_df["Close_XOM"]
xom_df = xom_df.drop(columns=["Date"])

unemployment_df = pd.read_csv("USUnemployment.csv", encoding = 'utf-8')

cci_df = pd.read_csv("CCI.csv", encoding='utf-8')

nasdaq_df = pd.read_csv("IXIC.csv", encoding='utf-8')
nasdaq_df.rename(columns={"Open":"Open_NASDAQ", "Close": "Close_NASDAQ"}, inplace = True)
nasdaq_df["Monthly_Change_NASDAQ"] = nasdaq_df["Open_NASDAQ"] - nasdaq_df["Close_NASDAQ"]
nasdaq_df = nasdaq_df.drop(columns=["Date"])

In [3]:
result = pd.concat([epd_df, kmi_df, mmp_df, mplx_df, nasdaq_df, et_df, xom_df], axis=1, join="outer")

In [4]:
result = result.dropna()
result = result.drop(columns=["High", "Low", "Adj Close", "Volume"])
result = result.iloc[1:]
final_result = result.iloc[:-1]

In [5]:
final_result

,Date,Open_EPD,Close_EPD,Monthly_Change_EPD,Open_KMI,Close_KMI,Monthly_Change_KMI,Open_MMP,Close_MMP,Monthly_Change_MMP,...,Monthly_Change_MPLX,Open_NASDAQ,Close_NASDAQ,Monthly_Change_NASDAQ,Open_ET,Close_ET,Monthly_Change_ET,Open_XOM,Close_XOM,Monthly_Change_XOM
1,2012-12-01,25.910000,25.040001,0.869999,34.060001,35.330002,-1.270001,44.470001,43.189999,1.280002,...,-2.290001,3091.330078,3142.129883,-50.799805,11.3700,11.3700,0.0000,87.790001,89.970001,-2.180000
2,2013-01-01,25.525000,28.334999,-2.809999,35.820000,37.459999,-1.639999,44.689999,50.610001,-5.920002,...,-2.819998,3162.939941,3160.189941,2.750000,20.0000,12.6400,7.3600,90.440002,89.550003,0.889999
3,2013-02-01,28.254999,28.334999,-0.080000,37.740002,37.070000,0.670002,50.910000,50.160000,0.750000,...,2.040001,3143.540039,3267.520020,-123.979981,12.7250,13.2975,-0.5725,89.070000,90.110001,-1.040001
4,2013-03-01,28.260000,30.145000,-1.885000,36.959999,38.680000,-1.720001,50.000000,53.430000,-3.430000,...,-4.670002,3268.629883,3328.790039,-60.160156,13.2425,23.2700,-10.0275,90.129997,88.989998,1.139999
5,2013-04-01,30.049999,30.325001,-0.275002,38.669998,39.099998,-0.430000,53.389999,53.029999,0.360000,...,-0.799999,3325.350098,3455.909912,-130.559814,14.5950,14.6700,-0.0750,88.519997,90.470001,-1.950004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2020-08-01,17.520000,17.559999,-0.039999,14.040000,13.820000,0.220000,40.500000,38.009998,2.490002,...,0.660000,11850.959961,11167.509766,683.450195,6.5700,6.4200,0.1500,39.750000,34.330002,5.419998
94,2020-09-01,17.510000,15.790000,1.720000,13.780000,12.330000,1.450000,37.959999,34.200001,3.759998,...,2.360000,11291.990234,10911.589844,380.400390,6.4200,5.4200,1.0000,33.790001,32.619999,1.170002
95,2020-10-01,15.760000,16.570000,-0.810000,12.200000,11.900000,0.300000,34.150002,35.540001,-1.389999,...,-1.499999,11010.450195,12198.740234,-1188.290039,5.4000,5.1500,0.2500,33.139999,38.130001,-4.990002
96,2020-11-01,16.639999,19.400000,-2.760001,12.030000,14.380000,-2.350000,36.150002,41.150002,-5.000000,...,-3.420000,12313.360352,12888.280273,-574.919921,5.1500,6.1800,-1.0300,38.959999,41.220001,-2.260002
97,2020-12-01,19.660000,19.590000,0.070000,14.670000,13.670000,1.000000,41.630001,42.439999,-0.809998,...,-0.350001,12958.519531,13070.690430,-112.170899,6.2600,6.1800,0.0800,41.450001,44.840000,-3.389999

In [6]:
unemployment_monthly = pd.DataFrame
unemployment_monthly_dates = []
unemployment_monthly_rates = []
for x in range(64,72):
    unemployment_monthly_rates.append(unemployment_df["Jan"][x])
    unemployment_monthly_rates.append(unemployment_df["Feb"][x])
    unemployment_monthly_rates.append(unemployment_df["Mar"][x])
    unemployment_monthly_rates.append(unemployment_df["Apr"][x])
    unemployment_monthly_rates.append(unemployment_df["May"][x])
    unemployment_monthly_rates.append(unemployment_df["Jun"][x])
    unemployment_monthly_rates.append(unemployment_df["Jul"][x])
    unemployment_monthly_rates.append(unemployment_df["Aug"][x])
    unemployment_monthly_rates.append(unemployment_df["Sep"][x])
    unemployment_monthly_rates.append(unemployment_df["Oct"][x])
    unemployment_monthly_rates.append(unemployment_df["Nov"][x])
    unemployment_monthly_rates.append(unemployment_df["Dec"][x])

unemployment_monthly_rates.append(3.6)
unemployment_monthly_rates.append(3.5)
unemployment_monthly_rates.append(4.4)
unemployment_monthly_rates.append(14.7)
unemployment_monthly_rates.append(13.3)
unemployment_monthly_rates.append(11.1)
unemployment_monthly_rates.append(10.2)
unemployment_monthly_rates.append(8.4)
unemployment_monthly_rates.append(7.8)
unemployment_monthly_rates.append(6.9)
unemployment_monthly_rates.append(6.7)
unemployment_monthly_rates.append(6.7)

del unemployment_monthly_rates[0:11]

In [7]:
final_result["Unemployment_Rate"] = unemployment_monthly_rates

<ipython-input-7-fd09ef57efe7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_result["Unemployment_Rate"] = unemployment_monthly_rates

In [8]:
cci_df_new = cci_df[cci_df["LOCATION"] == "USA"]

In [9]:
cci_df_new

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
1257,USA,CCI,AMPLITUD,LTRENDIDX,M,2012-12,98.65468,NaN
1258,USA,CCI,AMPLITUD,LTRENDIDX,M,2013-01,98.51059,NaN
1259,USA,CCI,AMPLITUD,LTRENDIDX,M,2013-02,98.62617,NaN
1260,USA,CCI,AMPLITUD,LTRENDIDX,M,2013-03,98.81338,NaN
1261,USA,CCI,AMPLITUD,LTRENDIDX,M,2013-04,99.05145,NaN
...,...,...,...,...,...,...,...,...
1349,USA,CCI,AMPLITUD,LTRENDIDX,M,2020-08,98.54670,NaN
1350,USA,CCI,AMPLITUD,LTRENDIDX,M,2020-09,98.88802,NaN
1351,USA,CCI,AMPLITUD,LTRENDIDX,M,2020-10,99.06155,NaN
1352,USA,CCI,AMPLITUD,LTRENDIDX,M,2020-11,99.04979,NaN
1353,USA,CCI,AMPLITUD,LTRENDIDX,M,2020-12,99.11961,NaN

In [10]:
cci_df_new_values = cci_df_new["Value"]
final_result["CCI_Values"] = cci_df_new_values.values

<ipython-input-10-8f4918266c30>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_result["CCI_Values"] = cci_df_new_values.values

In [11]:
final_result

,Date,Open_EPD,Close_EPD,Monthly_Change_EPD,Open_KMI,Close_KMI,Monthly_Change_KMI,Open_MMP,Close_MMP,Monthly_Change_MMP,...,Close_NASDAQ,Monthly_Change_NASDAQ,Open_ET,Close_ET,Monthly_Change_ET,Open_XOM,Close_XOM,Monthly_Change_XOM,Unemployment_Rate,CCI_Values
1,2012-12-01,25.910000,25.040001,0.869999,34.060001,35.330002,-1.270001,44.470001,43.189999,1.280002,...,3142.129883,-50.799805,11.3700,11.3700,0.0000,87.790001,89.970001,-2.180000,7.9,98.65468
2,2013-01-01,25.525000,28.334999,-2.809999,35.820000,37.459999,-1.639999,44.689999,50.610001,-5.920002,...,3160.189941,2.750000,20.0000,12.6400,7.3600,90.440002,89.550003,0.889999,8.0,98.51059
3,2013-02-01,28.254999,28.334999,-0.080000,37.740002,37.070000,0.670002,50.910000,50.160000,0.750000,...,3267.520020,-123.979981,12.7250,13.2975,-0.5725,89.070000,90.110001,-1.040001,7.7,98.62617
4,2013-03-01,28.260000,30.145000,-1.885000,36.959999,38.680000,-1.720001,50.000000,53.430000,-3.430000,...,3328.790039,-60.160156,13.2425,23.2700,-10.0275,90.129997,88.989998,1.139999,7.5,98.81338
5,2013-04-01,30.049999,30.325001,-0.275002,38.669998,39.099998,-0.430000,53.389999,53.029999,0.360000,...,3455.909912,-130.559814,14.5950,14.6700,-0.0750,88.519997,90.470001,-1.950004,7.6,99.05145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2020-08-01,17.520000,17.559999,-0.039999,14.040000,13.820000,0.220000,40.500000,38.009998,2.490002,...,11167.509766,683.450195,6.5700,6.4200,0.1500,39.750000,34.330002,5.419998,8.4,98.54670
94,2020-09-01,17.510000,15.790000,1.720000,13.780000,12.330000,1.450000,37.959999,34.200001,3.759998,...,10911.589844,380.400390,6.4200,5.4200,1.0000,33.790001,32.619999,1.170002,7.8,98.88802
95,2020-10-01,15.760000,16.570000,-0.810000,12.200000,11.900000,0.300000,34.150002,35.540001,-1.389999,...,12198.740234,-1188.290039,5.4000,5.1500,0.2500,33.139999,38.130001,-4.990002,6.9,99.06155
96,2020-11-01,16.639999,19.400000,-2.760001,12.030000,14.380000,-2.350000,36.150002,41.150002,-5.000000,...,12888.280273,-574.919921,5.1500,6.1800,-1.0300,38.959999,41.220001,-2.260002,6.7,99.04979
97,2020-12-01,19.660000,19.590000,0.070000,14.670000,13.670000,1.000000,41.630001,42.439999,-0.809998,...,13070.690430,-112.170899,6.2600,6.1800,0.0800,41.450001,44.840000,-3.389999,6.7,99.11961

In [12]:
final_result

,Date,Open_EPD,Close_EPD,Monthly_Change_EPD,Open_KMI,Close_KMI,Monthly_Change_KMI,Open_MMP,Close_MMP,Monthly_Change_MMP,...,Close_NASDAQ,Monthly_Change_NASDAQ,Open_ET,Close_ET,Monthly_Change_ET,Open_XOM,Close_XOM,Monthly_Change_XOM,Unemployment_Rate,CCI_Values
1,2012-12-01,25.910000,25.040001,0.869999,34.060001,35.330002,-1.270001,44.470001,43.189999,1.280002,...,3142.129883,-50.799805,11.3700,11.3700,0.0000,87.790001,89.970001,-2.180000,7.9,98.65468
2,2013-01-01,25.525000,28.334999,-2.809999,35.820000,37.459999,-1.639999,44.689999,50.610001,-5.920002,...,3160.189941,2.750000,20.0000,12.6400,7.3600,90.440002,89.550003,0.889999,8.0,98.51059
3,2013-02-01,28.254999,28.334999,-0.080000,37.740002,37.070000,0.670002,50.910000,50.160000,0.750000,...,3267.520020,-123.979981,12.7250,13.2975,-0.5725,89.070000,90.110001,-1.040001,7.7,98.62617
4,2013-03-01,28.260000,30.145000,-1.885000,36.959999,38.680000,-1.720001,50.000000,53.430000,-3.430000,...,3328.790039,-60.160156,13.2425,23.2700,-10.0275,90.129997,88.989998,1.139999,7.5,98.81338
5,2013-04-01,30.049999,30.325001,-0.275002,38.669998,39.099998,-0.430000,53.389999,53.029999,0.360000,...,3455.909912,-130.559814,14.5950,14.6700,-0.0750,88.519997,90.470001,-1.950004,7.6,99.05145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2020-08-01,17.520000,17.559999,-0.039999,14.040000,13.820000,0.220000,40.500000,38.009998,2.490002,...,11167.509766,683.450195,6.5700,6.4200,0.1500,39.750000,34.330002,5.419998,8.4,98.54670
94,2020-09-01,17.510000,15.790000,1.720000,13.780000,12.330000,1.450000,37.959999,34.200001,3.759998,...,10911.589844,380.400390,6.4200,5.4200,1.0000,33.790001,32.619999,1.170002,7.8,98.88802
95,2020-10-01,15.760000,16.570000,-0.810000,12.200000,11.900000,0.300000,34.150002,35.540001,-1.389999,...,12198.740234,-1188.290039,5.4000,5.1500,0.2500,33.139999,38.130001,-4.990002,6.9,99.06155
96,2020-11-01,16.639999,19.400000,-2.760001,12.030000,14.380000,-2.350000,36.150002,41.150002,-5.000000,...,12888.280273,-574.919921,5.1500,6.1800,-1.0300,38.959999,41.220001,-2.260002,6.7,99.04979
97,2020-12-01,19.660000,19.590000,0.070000,14.670000,13.670000,1.000000,41.630001,42.439999,-0.809998,...,13070.690430,-112.170899,6.2600,6.1800,0.0800,41.450001,44.840000,-3.389999,6.7,99.11961

In [13]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge

features = final_result[["Monthly_Change_KMI","Monthly_Change_MPLX", "CCI_Values"]]
target = final_result["Monthly_Change_ET"]

X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=1)

def RFE_feature_selection():
    
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    
    select = RFE(DecisionTreeRegressor(random_state=1), n_features_to_select=3)
    
    #fit the RFE selector to the training data
    select.fit(X_train, y_train)

    #transform training and testing sets so only the selected features are retained
    X_train_selected = select.transform(X_train)
    X_test_selected = select.transform(X_test)
    
    model = Ridge().fit(X=X_train_selected, y=y_train)
    
    print("Selected features after RFE:")
    for i in range(len(select.get_support())):
        if select.get_support()[i]:
            print(features.columns[i]) #gets the features for which get_support is true
    
    accuracy_train = model.score(X_train_selected, y_train)
    accuracy_test = model.score(X_test_selected, y_test)

    print("\nkNN Classification performance with selected features:")
    print("\t Prediction accuracy on the train data:", f"{accuracy_train:.2%} \n")
    print("\t Prediction accuracy on the test data:", f"{accuracy_test:.2%} \n")

RFE_feature_selection()

Selected features after RFE:
Monthly_Change_KMI
Monthly_Change_MPLX
CCI_Values

kNN Classification performance with selected features:
	 Prediction accuracy on the train data: 34.10%

	 Prediction accuracy on the test data: 40.69%

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import LinearSVR

estimators = {
    'Linear Regression': LinearRegression(), 
    'Ridge': Ridge(alpha = 0.001),
    'Lasso': Lasso(alpha = 0.001),
    'K-Nearest Neighbors Regressor': KNeighborsRegressor(n_neighbors = 3),
    'Linear SVC': LinearSVR(C=0.01, max_iter = 100)
}

In [15]:
from sklearn.preprocessing import MinMaxScaler
def regressors_percentage_split():
    X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=37)
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    for estimator_name, estimator_object in estimators.items():
        estimator_object.fit(X=X_train_scaled, y=y_train)
        accuracy = estimator_object.score(X_test_scaled, y_test)
        print(estimator_name)
        print("\t Prediction accuracy on the test data:", f"{accuracy:.2%} \n")

In [16]:
regressors_percentage_split()

Linear Regression
	 Prediction accuracy on the test data: 69.24%

Ridge
	 Prediction accuracy on the test data: 69.22%

Lasso
	 Prediction accuracy on the test data: 68.87%

K-Nearest Neighbors Regressor
	 Prediction accuracy on the test data: 43.36%

Linear SVC
	 Prediction accuracy on the test data: -1.69%

In [17]:
param_grid = {"alpha":[0.001, 0.01, 0.1, 1, 10, 100]}

from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

#import GridSearchCV and fit GridSearchCV
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(Ridge(), param_grid, cv=5)

#split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=3000)

#fit the grid search object on the training data (CV will be performed on this)
grid_search.fit(X=X_train, y=y_train)

#result of grid search
print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)

#the performance of the best found parameters on the test set
#this is what you report for the evaluation of your model
print("Test set score: ", grid_search.score(X_test, y_test))

Best parameters:  {'alpha': 100}
Best cross-validation score:  0.2981611159228531
Test set score:  0.34695937575834257

In [18]:
model = Lasso(alpha=0.001).fit(X=X_train, y=y_train)

In [19]:
model.predict([[0.005, -5.123, 98.67]])

array([-1.07411308])

In [20]:
import pickle
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [ ]:
import os
import pandas as pd 
import numpy as np 
import flask
import pickle
from flask import Flask, render_template, request

app=Flask(__name__)
@app.route('/')
def index():
    return flask.render_template('index.html')

def ValuePredictor(to_predict_list):
    to_predict = np.array(to_predict_list)
    loaded_model = pickle.load(open('model_pickle','rb'))
    result = loaded_model.predict(to_predict)
    return result[0]
@app.route('/predict',methods = ['POST'])
def result():
    if request.method == 'POST':
        to_predict_list = request.form.to_dict()
        to_predict_list= list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        result = ValuePredictor([to_predict_list])
        prediction = str(result)
    return render_template('predict.html',prediction=prediction)
if __name__ == '__main__':
    app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Feb/2021 11:51:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/Feb/2021 11:51:45] "POST /predict HTTP/1.1" 200 -